### ISSUE TITLE
reactive mode rule execution order

### ISSUE THREAD

**Issue by bthibault** [C2FO/nools#145]
I'm operating in reactive mode streaming thousands of facts to the rules engine.

I have a few rules built: lets call them rule_0 , rule_1, rule_2, 

When I stream facts in 

I get this execution order 

rule_0 fired  
rule_0 fired
rule_0 fired
rule_0 fired
...
...
...
rule_1 fired
rule_1 fired
rule_1 fired
...

What I want is this order 

rule_0
rule_1
rule_2

rule_0
rule_1
rule_2

I have it working now, by significantly modifying my code to implement some pausing and blocking and fact aggregation to get this execution order, 

When I execute not in streaming mode, i get the desired execution order. 

my question is is there a way to make this work with in Nools itself?

**Comment by doug-martin** [comment]
I have a feeling it has to do with fact recency, but I may be wrong. But I would guess that when facts are streamed in the newest fact asserted causes its rule to fire first since it is the newest, if you read the section about [Conflict Resolution](https://github.com/C2FO/nools#conflict-resolution) it dives deeper into this. You might also playing with the strategy which that section also talks about. 

If you can come up with an example I may be able to help with this or if there is an issue I could come up with a test, or a new conflict resolution strategy to help alleviate this scenario.

**Comment by bthibault** [comment]
Okay thanks, conflict resolution may solve my problem. I kind of skipped over that section... :) 

FYI using nools in production starting soon. Very nice tool

**Comment by doug-martin** [comment]
Awesome! If you want to you could add a section to the readme about who is using nools in production and add yourself (Im assuming ClaraStream), I'll also add C2FO....Thanks for your feedback and commenting on issues!
