### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by k1tzu** [C2FO/nools#156]
Using nools leads to constant memory growth. Correct me if I'm wrong.
Here's the sample code:

```js
var nools = require("nools");

var Message = function (message) {
    this.value = message;
};

var flow = nools.flow("custom contraint", function (flow) {
    flow.rule("hello rule", [Message, "m", "m.value == 12345"], function (facts) {
        console.log(Message);
    });
});

var session = flow.getSession();

setInterval(function () {
    var msg = new Message(Math.floor(Math.random() * Number.MAX_VALUE));
    session.assert(msg);
    session.retract(msg);
}, 1);
```

//Linux 4.1.6-1-ARCH
//node v4.1.0

**Comment by hugoduraes** [comment]
I've noticed this too! Have you had any luck in finding the issue?

**Comment by k1tzu** [comment]
No, I switched to node-rules

**Comment by hugoduraes** [comment]
@doug-martin can you have a look at this?

Just by asserting and retracting facts, the memory usage never stops growing!

**Comment by PauloASilva** [comment]
@k1tzu When testing your example we (I am @hugoduraes' co-worker) did believe that there was a memory leak. In fact, memory keeps growing and when inspecting Node's heap, lots of strings are left behind (something like +213 078 Strings) which are related with Nools' `rootNode` (one of its internal structures).

After a bunch of debugging hours, memory analysis and reading we concluded that Node's VM memory policies (GC) is somehow, fuzzy, so we decided to understand exactly how Nools' memory grows.

We did look inside heap on three different moments on a scenario with 1540 rules (DSL) and 800 facts (bigger than your `Message`):

1. script bootstrap (before DSL compilation):     6.39MB 
2. after DSL compilation (1540 rules)            :   15.05MB
3. after facts (800) assertion                           : 661.77MB
4. after match (`retract()` is called on fire)    :    30.99MB

I can provide you more details but between each step the increase is due to `Array`, `Object` and `String` allocation.

The point here is that after `match()`ing (even without calling `dispose()`), heap size decreased as expected.

With this knowledge we will process Facts by chunks. This way we expect to keep Nools' memory footprint quite stable.
This approach should also "help" with `dispose()` `Maximum call stack size exceeded` for large facts set.

It would be nice to hear from you.

**Comment by k1tzu** [comment]
The thing is I need to keep a facts database of a certain size. I tried to do that by retracting oldest facts from it. But I still can't find the way to do that without memory leak.
```javascript
session.assert(msg);
session.match(function(){
	session.retract(msg);
});
```
doesn't work - still leaks.

Can you post a sample code that adds new fact and retract an older fact and doesn't lead to a leak.

**Comment by scaryguy** [comment]
Guys, I was considering to start using nools in my project but this topic freaked me out. 

Do you think that it's not a good idea to use nools? Would you recommend node-rules instead?

**Comment by DevSide** [comment]
I fixed it. 

@scaryguy, it depends on your needs. node-rules is a rule engine while nools is an inference engine.
